export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILED = "SEARCH_FAILED";

export const SEARCH_HISTORY_REQUEST = "SEARCH_HISTORY_REQUEST";
export const SEARCH_HISTORY_SUCCESS = "SEARCH_HISTORY_SUCCESS";
export const SEARCH_HISTORY_FAILED = "SEARCH_HISTORY_FAILED";

export const SEARCH_POST_HISTORY_REQUEST = "SEARCH_POST_HISTORY_REQUEST";
export const SEARCH_POST_HISTORY_SUCCESS = "SEARCH_POST_HISTORY_SUCCESS";
export const SEARCH_POST_HISTORY_FAILED = "SEARCH_POST_HISTORY_FAILED";

export const DELETE_HISTORY_REQUEST = "DELETE_HISTORY_REQUEST";
export const DELETE_HISTORY_SUCCESS = "DELETE_HISTORY_SUCCESS";
export const DELETE_HISTORY_FAILED = "DELETE_HISTORY_FAILED";

