export const GET_DISCOUNT_REQUEST = "GET_DISCOUNT_REQUEST";
export const GET_DISCOUNT_SUCCESS = "GET_DISCOUNT_SUCCESS";
export const GET_DISCOUNT_FAILED = "GET_DISCOUNT_FAILED";

export const GET_FILTER_COUPON_PRODUCT_REQUEST = "GET_FILTER_COUPON_PRODUCT_REQUEST";
export const GET_FILTER_COUPON_PRODUCT_SUCCESS = "GET_FILTER_COUPON_PRODUCT_SUCCESS";
export const GET_FILTER_COUPON_PRODUCT_FAILED = "GET_FILTER_COUPON_PRODUCT_FAILED";

export const APPLY_COUPON_REQUEST = "APPLY_COUPON_REQUEST";
export const APPLY_COUPON_SUCCESS = "APPLY_COUPON_SUCCESS";
export const APPLY_COUPON_FAILED = "UNAPPLY_COUPON_FAILED";

export const UNAPPLY_COUPON_REQUEST = "UNAPPLY_COUPON_REQUEST";
export const UNAPPLY_COUPON_SUCCESS = "UNAPPLY_COUPON_SUCCESS";
export const UNAPPLY_COUPON_FAILED = "UNAPPLY_COUPON_FAILED";

export const TOTAL_DISCOUNT_TO_PRODUCT = "TOTAL_DISCOUNT_TO_PRODUCT";